Repository AliceO2Group/O2DPG, pull requests merged in 2024-04, with the labels that each got.

#1567 Use inelastic XS for nuclei
  MC/config/PWGLF/xsection/g4config_had_x2.in
Labels: async-2022-pp-apass4, async-2023-pbpb-apass, async-mc, async-2022-pp-apass6

#1570 Use proper hadronic process for the different nuclear species
  MC/config/PWGLF/xsection/g4config_had_x2.in
Labels: async-2022-pp-apass4, async-2023-pbpb-apass, async-mc, async-2022-pp-apass6

#1556 [SimWF] Set MCANCHOR to value of LPMANCHORPASSNAME
  MC/bin/o2dpg_sim_workflow.py
Labels: async-2022-pp-apass4, async-2023-pbpb-apass, async-2023-pp-apass1, async-mc, async-2022-pp-apass6

#1575 Adjust matching chi2 cut to 80 for pbpb
  DATA/production/configurations/asyncReco/setenv_extra.sh
Labels: async-2023-pbpb-apass

#1580 Update Resonance injection scripts
  MC/config/PWGLF/ini/GeneratorLF_Resonances_PbPb5360_injection.ini
  MC/config/PWGLF/ini/GeneratorLF_Resonances_PbPb5360_trigger.ini
  MC/config/PWGLF/ini/GeneratorLF_Resonances_pp1360_injection.ini
  MC/config/PWGLF/ini/GeneratorLF_Resonances_pp1360_trigger.ini
  MC/config/PWGLF/ini/GeneratorLF_Resonances_pp900_injection.ini
  MC/config/PWGLF/ini/GeneratorLF_Resonances_pp900_trigger.ini
  MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_PbPb5360_injection.C
  MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_PbPb5360_trigger.C
  MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_pp1360_injection.C
  MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_pp1360_trigger.C
  MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_pp900_injection.C
  MC/config/PWGLF/ini/tests/GeneratorLF_Resonances_pp900_trigger.C
  MC/config/PWGLF/pythia8/generator/resonancelistgun_inj.json
  MC/config/PWGLF/pythia8/generator/resonancelistgun_trig.json
Labels: async-2022-pp-apass4, async-2023-pbpb-apass, async-2023-pp-apass1, async-mc

#1589 Possibility to set delay to 0
  DATA/production/configurations/asyncReco/async_pass.sh
Labels: async-data

#1587 Fix options for collision context creation in (old) embedding path
  MC/bin/o2dpg_sim_workflow.py
Labels: async-2022-pp-apass4, async-2023-pbpb-apass, async-2023-pp-apass1, async-2022-pp-apass6-2023-PbPb-apass2

#1583 MC/config/PWGEM: add Generator.C and ini for LF->ee/gamma in PWGEM
  MC/config/PWGEM/external/generator/GeneratorCocktailWithGap.C
  MC/config/PWGEM/external/generator/Generator_pythia8_GapTriggered_LFee.C
  MC/config/PWGEM/external/generator/Generator_pythia8_GapTriggered_LFgamma.C
  MC/config/PWGEM/ini/Generator_GapTriggered_LFee.ini
  MC/config/PWGEM/ini/Generator_GapTriggered_LFgamma.ini
  MC/config/PWGEM/ini/tests/Generator_GapTriggered_LFee.C
  MC/config/PWGEM/ini/tests/Generator_GapTriggered_LFgamma.C
Labels: async-mc, async-2022-pp-apass6-2023-PbPb-apass2

#1594 [AnalysisQC] Align some depending code
  MC/analysis_testing/analysis_test.sh
  MC/analysis_testing/o2dpg_analysis_test_config.py
  MC/analysis_testing/o2dpg_analysis_test_utils.py
  MC/analysis_testing/o2dpg_analysis_test_workflow.py
Labels: async-2022-pp-apass4, async-2022-pp-apass6-2023-PbPb-apass2

#1598 Enable strangeness tracking by default
  MC/bin/o2dpg_sim_workflow.py
  MC/run/PWGLF/run_HyperNucleiInjectedGap.sh
  MC/run/PWGLF/run_StrangenessInjected.sh
  MC/run/PWGLF/run_StrangenessTriggered.sh
Labels: async-2023-pbpb-apass3, async-2023-pbpb-apass4, mc, async-2022-pp-apass6-2023-PbPb-apass2

#1600 [AnalysisQC] Small fix, add comments
  MC/analysis_testing/o2dpg_analysis_test_config.py
Labels: async-2022-pp-apass4, async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2022-pp-apass6-2023-PbPb-apass2

#1597 [Anchor] Use STF and ETF
  MC/bin/o2dpg_sim_workflow_anchored.py
Labels: async-2022-pp-apass4, async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2022-pp-apass6-2023-PbPb-apass2

#1604 PWGLF: Disable generator for the injection script
  MC/config/PWGLF/ini/GeneratorLF_Resonances_PbPb5360_injection.ini
Labels: async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2022-pp-apass6-2023-PbPb-apass2

#1507 TPC: Add possibility to simulate distortions
  MC/bin/o2dpg_sim_workflow.py
  MC/bin/o2dpg_sim_workflow_anchored.py
Labels: async-2023-pbpb-apass3, async-2023-pbpb-apass4

#1501 Create ITS/MFT light geom snapshots together with geometry-aligned
  MC/run/ANCHOR/anchorMC.sh
Labels: mc
