Repository AliceO2Group/O2DPG, pull requests merged in 2024-03, with the labels that each got.

#1514 [AnalysisQC] Make common args better adjustable
  MC/analysis_testing/o2dpg_analysis_test_utils.py
  MC/analysis_testing/o2dpg_analysis_test_workflow.py
  MC/config/analysis_testing/json/analyses_config.json
Labels: async-2023-pbpb-apass, async-2023-pp-apass1, async-data, async-mc

#1513 [Anchor] Remove -k from QC run, return error code
  MC/run/ANCHOR/anchorMC.sh
Labels: async-2022-pp-apass4, async-2023-pbpb-apass, async-2023-pp-apass1, async-mc, async-2022-pp-apass6

#1516 Possibility to take QC alone when we split the wf
  DATA/production/configurations/asyncReco/async_pass.sh
Labels: async-data

#1518 [SimWF] Use __global_init_task__ more consistently
  MC/analysis_testing/o2dpg_analysis_test_workflow.py
  MC/bin/o2dpg_sim_workflow.py
  MC/bin/o2dpg_workflow_utils.py
Labels: async-2022-pp-apass4, async-2023-pbpb-apass, async-2023-pp-apass1, async-mc, async-2022-pp-apass6

#1531 porting of MID aQC workflow to MC
  MC/bin/o2dpg_qc_finalization_workflow.py
  MC/bin/o2dpg_sim_workflow.py
  MC/config/QC/json/mid-task.json
Labels: async-2023-pbpb-apass, async-2023-pp-apass1, async-mc

#1534 Update Lambda1520 pdg code
  MC/config/PWGLF/pythia8/generator/resonancelist.gun
  MC/config/PWGLF/pythia8/generator/resonancelistgun.json
  MC/config/PWGLF/pythia8/generator/resonances.cfg
Labels: async-2022-pp-apass4, async-2023-pbpb-apass, async-mc

#1536 TPC reco needs CTP digits
  MC/bin/o2dpg_sim_workflow.py
Labels: async-2022-pp-apass4, async-2023-pbpb-apass, async-2023-pp-apass1, async-data, async-mc, async-2022-pp-apass6

#1532 [WFRunner] Handle resource limits and CPU better
  MC/bin/o2_dpg_workflow_runner.py
Labels: async-2022-pp-apass4, async-2023-pbpb-apass, async-2023-pp-apass1, async-mc, async-2022-pp-apass6

#1552 Enhance fraction of D+ to KKpi in D2H MC + new configuration
  MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_and_bbbar_gap3_Mode2.ini
  MC/config/PWGHF/ini/tests/GeneratorHF_D2H_ccbar_and_bbbar_gap3_Mode2.C
  MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays.cfg
  MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_Mode2.cfg
Labels: async-2022-pp-apass4, async-2022-pp-apass6

#1551 [SimWF] Protect the -e argument
  MC/bin/o2dpg_sim_workflow.py
Labels: async-2022-pp-apass4, async-2023-pbpb-apass, async-2023-pp-apass1, async-mc, async-2022-pp-apass6

#1553 PWGHF: Add configuration for sim with pT-hard bins (no gap)
  MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_and_bbbar_Mode2_ptHardBins.ini
  MC/config/PWGHF/ini/tests/GeneratorHF_D2H_ccbar_and_bbbar_Mode2_ptHardBins.C
  MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_Mode2_ptHardBins.cfg
Labels: async-2022-pp-apass4, async-2022-pp-apass6

#1545 Updates to reduce memory consumption and allow DPG to turn off sampling in validation
  DATA/production/qc-async/tpc.json
Labels: async-data

#1538 CPV, PHS: update qc-async json config according to QC review 2023
  DATA/production/qc-async/cpv.json
  DATA/production/qc-async/phs.json
Labels: async-data

#1539 Prototype decouple event gen from transport
  MC/bin/o2dpg_sim_workflow.py
  MC/run/ANCHOR/anchorMC.sh
  MC/run/ANCHOR/tests/test_anchor_2023_apass2_pp.sh
Labels: async-2022-pp-apass6
