Repository AliceO2Group/O2DPG, pull requests merged in 2024-09, with the labels that each got.

#1740 Fix TPC timeseries for MC
  MC/bin/o2dpg_sim_workflow.py
Labels: async-2023-pbpb-apass4

#1743 PWGHF: add config for Pb-Pb MCs without pt hard bins for signal
  MC/config/PWGHF/external/generator/generator_pythia8_embed_hf.C
  MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_and_bbbar_PbPb_ptHardBins.ini
  MC/config/PWGHF/ini/tests/GeneratorHF_D2H_ccbar_and_bbbar_PbPb_ptHardBins.C
Labels: async-2023-pbpb-apass4, async-2023-pp-apass4, async-2024-pp-apass1, async-2022-pp-apass7

#1730 Added possibility to define a general HEPMCOFFSET.
  MC/bin/o2dpg_sim_workflow.py
  UTILS/InitHepMCEventSkip.sh
  UTILS/ReadHepMCEventSkip.sh
Labels: async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2023-pp-apass4, async-2024-pp-apass1, async-2022-pp-apass7, async-2024-pp-cpass0
