Repository AliceO2Group/O2DPG, pull requests merged in 2024-07, with the labels that each got.

#1686 Add --run to alignment geometry creation
  MC/run/ANCHOR/anchorMC.sh
Labels: async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2023-pp-apass4, async-2024-pp-apass1, async-2022-pp-apass7, async-2024-pp-cpass0

#1698 Doing the check on unmerged and then merged AODs in the parallelized …
  DATA/production/configurations/asyncReco/async_pass.sh
Labels: async-2024-pp-apass1, async-2024-pp-cpass0

#1702 Revert "ZDC: Add configuration file PbPb, modify configuration file pp, add s…"
  DATA/production/qc-async/zdc.json
  DATA/production/qc-async/zdcPbPb.json
  DATA/production/qc-workflow.sh
Labels: async-2023-pbpb-apass4, async-2024-pp-apass1, async-2024-pp-cpass0

#1696 Set the analysisQC axis range depending on the coll system
  MC/analysis_testing/o2dpg_analysis_test_utils.py
  MC/config/analysis_testing/json/dpl/o2-analysis-qa-event-track.json
Labels: async-2024-pp-apass1, async-2024-pp-cpass0

#1709 PWGHF: restore SigmaC0 decays in MC config.
  MC/config/PWGHF/pythia8/decayer/force_hadronic_D.cfg
  MC/config/PWGHF/pythia8/generator/pythia8_beautyhadronic_with_decays_Mode2.cfg
  MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays.cfg
  MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_Mode2.cfg
  MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_Mode2_hardQCD_5TeV.cfg
  MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_Mode2_ptHardBins.cfg
  MC/config/PWGHF/pythia8/generator/pythia8_charmtriggers_with_Bforced_decay.cfg
  MC/config/PWGHF/pythia8/generator/pythia8_charmtriggers_with_decays.cfg
Labels: async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2023-pp-apass4, async-2024-pp-apass1, async-2022-pp-apass7

#1710 PWGHF: add ini for D resonances MCs for pp collisions
  MC/config/PWGHF/ini/GeneratorHF_D2H_ccbar_and_bbbar_gap5_DReso.ini
  MC/config/PWGHF/ini/tests/GeneratorHF_D2H_ccbar_and_bbbar_gap5_DReso.C
  MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_DReso.cfg
Labels: async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2023-pp-apass4, async-2024-pp-apass1, async-2022-pp-apass7

#1713 Activate non-invasive UPC settings for pbpb reconstruction
  DATA/production/configurations/asyncReco/setenv_extra.sh
Labels: async-2023-pbpb-apass4

#1715 PWGHF: adjust mother-daughter indexing in generator
  MC/config/PWGHF/external/generator/generator_pythia8_embed_hf.C
Labels: async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2023-pp-apass4, async-2024-pp-apass1, async-2022-pp-apass7
