Repository AliceO2Group/O2DPG, pull requests merged in 2024-05, with the labels that each got.

#1634 Restore space in the var. expansion and add default ALIEN_PROC_ID
  DATA/production/common/setVarsFromALIEN_PROC_ID.sh
Labels: async-2022-pp-apass7, async-2024-pp-cpass0

#1638 Pythia8 events with pt>ptLeading and PDG of interest
  MC/config/PWGLF/ini/GeneratorLF_HighPt.ini
  MC/config/PWGLF/ini/tests/GeneratorLF_HighPt.C
  MC/config/PWGLF/pythia8/generator_pythia8_highpt.C
  MC/run/PWGLF/run_GeneratorLF_highpt.sh
Labels: async-2022-pp-apass4, async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2022-pp-apass6-2023-PbPb-apass2

#1624 TPC: Update stochastic cluster and systematic track errors
  DATA/production/configurations/asyncReco/setenv_extra.sh
Labels: async-2023-pbpb-apass4

#1639 pythia8 events with (anti)deuterons and high pt
  MC/config/PWGLF/ini/GeneratorLF_antid_and_highpt.ini
  MC/config/PWGLF/ini/tests/GeneratorLF_antid_and_highpt.C
  MC/config/PWGLF/pythia8/generator_pythia8_antid_and_highpt.C
  MC/run/PWGLF/run_GeneratorLF_antid_and_highpt.sh
Labels: async-2022-pp-apass4, async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2022-pp-apass6-2023-PbPb-apass2

#1607 Remove option ctp-readout-create
  MC/bin/o2dpg_sim_workflow.py
Labels: async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2022-pp-apass6-2023-PbPb-apass2

#1646 pythia8 for pp with pt>ptLeading and random strange hadron
  MC/config/PWGLF/ini/GeneratorLF_highpt_strangeness.ini
  MC/config/PWGLF/ini/tests/GeneratorLF_highpt_strangeness.C
  MC/config/PWGLF/pythia8/generator_pythia8_highpt_strangeness.C
  MC/run/PWGLF/run_GeneratorLF_highpt_strangeness.sh
Labels: async-2022-pp-apass4, async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2022-pp-apass6-2023-PbPb-apass2
