Repository AliceO2Group/O2DPG, pull requests merged in 2024-08, with the labels that each got.

#1718 Add D0 decay in K pi pi0
  MC/config/PWGHF/pythia8/generator/pythia8_beautyhadronic_with_decays_Mode2.cfg
  MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays.cfg
  MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_Mode2.cfg
  MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_Mode2_hardQCD_5TeV.cfg
  MC/config/PWGHF/pythia8/generator/pythia8_charmhadronic_with_decays_Mode2_ptHardBins.cfg
  MC/config/PWGHF/pythia8/generator/pythia8_charmtriggers_with_Bforced_decay.cfg
  MC/config/PWGHF/pythia8/generator/pythia8_charmtriggers_with_decays.cfg
Labels: async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2023-pp-apass4, async-2024-pp-apass1, async-2022-pp-apass7

#1721 Synthetic flow generator added
  MC/config/PWGLF/ini/GeneratorLF_SyntheFlow.ini
  MC/config/PWGLF/ini/tests/GeneratorLF_SyntheFlow.C
  MC/config/PWGLF/pythia8/generator_pythia8_syntheFlow.C
Labels: async-2023-pbpb-apass4, async-2024-pp-apass1, async-2022-pp-apass7, async-2024-pp-cpass0

#1731 Minor fix to generator_pythia8_LF.C
  MC/config/PWGLF/pythia8/generator_pythia8_LF.C
Labels: async-2023-pbpb-apass4, async-2022-pp-apass7

#1739 Start special treatment of IROC11 hole from run 544512 instead of 544511
  DATA/production/configurations/asyncReco/setenv_extra.sh
Labels: async-2023-pp-apass4
